#ifndef __BINDLESS_INDICES_HLSLI__
#define __BINDLESS_INDICES_HLSLI__

#define BINDLESS_CAPACITY  1024
#define BINDLESS_UAV_BASE  768

#define SRV_GROUP_COMMON_BASE      0
#define SRV_GROUP_GEOMETRY_BASE    32
#define SRV_GROUP_CULLING_BASE	   64
#define SRV_GROUP_LIGHTING_BASE    128
#define SRV_GROUP_POST_BASE        384
#define SRV_GROUP_MESHLET_BASE     512

#define UAV_GROUP_CULLING_BASE     BINDLESS_UAV_BASE + 0
#define UAV_GROUP_SCENE_BASE       BINDLESS_UAV_BASE + 64
#define UAV_GROUP_LIGHTING_BASE    BINDLESS_UAV_BASE + 96
#define UAV_GROUP_POST_BASE        BINDLESS_UAV_BASE + 128

#define SRV_IBL_CUBE_MAP           (SRV_GROUP_COMMON_BASE + 0)
#define SRV_IBL_DIFFUSE_LD         (SRV_GROUP_COMMON_BASE + 1)
#define SRV_IBL_SPECULAR_LD        (SRV_GROUP_COMMON_BASE + 2)
#define SRV_IBL_LUT                (SRV_GROUP_COMMON_BASE + 3)
#define SRV_SHADOW_MAP             (SRV_GROUP_COMMON_BASE + 4)
#define SRV_SSAO                   (SRV_GROUP_COMMON_BASE + 5)
#define SRV_INDIRECT_COMMANDS_BASE (SRV_GROUP_CULLING_BASE + 0)
#define SRV_INDIRECT_VISIBLE_FLAGS_BASE (SRV_GROUP_CULLING_BASE + 8)
#define SRV_INDIRECT_CULLING_RESULTS_BASE (SRV_GROUP_CULLING_BASE + 16)
#define SRV_INDIRECT_CULLING_RESULTS_COUNTER_BASE (SRV_GROUP_CULLING_BASE + 24)

#define SRV_LIGHT_BUFFER           (SRV_GROUP_LIGHTING_BASE + 0)
#define SRV_LIGHT_SHADOW_ARRAY     (SRV_GROUP_LIGHTING_BASE + 1)
#define SRV_LIGHT_GRID             (SRV_GROUP_LIGHTING_BASE + 2)
#define SRV_LIGHT_GRID_MASK        (SRV_GROUP_LIGHTING_BASE + 3)
#define SRV_SCENE_COLOR            (SRV_GROUP_POST_BASE + 0)
#define SRV_GBUFFER_A              (SRV_GROUP_POST_BASE + 1)
#define SRV_GBUFFER_B              (SRV_GROUP_POST_BASE + 2)
#define SRV_GBUFFER_C              (SRV_GROUP_POST_BASE + 3)
#define SRV_GBUFFER_D              (SRV_GROUP_POST_BASE + 4)
#define SRV_SCENE_DEPTH            (SRV_GROUP_POST_BASE + 5)
#define SRV_SCENE_STENCIL          (SRV_GROUP_POST_BASE + 6)
#define SRV_SCENE_HZB0			   (SRV_GROUP_POST_BASE + 7)
#define SRV_SCENE_HZB1			   (SRV_GROUP_POST_BASE + 8)
#define SRV_VBUFFER                (SRV_GROUP_POST_BASE + 9)

#define SRV_MESH_CONSTANTS_BUFFER	  (SRV_GROUP_MESHLET_BASE + 0)
#define SRV_MATERIAL_CONSTANTS_BUFFER (SRV_GROUP_MESHLET_BASE + 1)
#define SRV_VERTEX_BUFFER      (SRV_GROUP_MESHLET_BASE + 2)
#define SRV_JOINTS_BUFFER      (SRV_GROUP_MESHLET_BASE + 3)
#define SRV_MESHLET_BUFFER     (SRV_GROUP_MESHLET_BASE + 4)
#define SRV_INSTANCE_CONSTANTS_BUFFER    (SRV_GROUP_MESHLET_BASE + 5)
#define SRV_INDEX_BUFFER       (SRV_GROUP_MESHLET_BASE + 6)
#define SRV_GEOMETRY_BUFFER       (SRV_GROUP_MESHLET_BASE + 7)

// UAV
#define UAV_INDIRECT_VISIBLE_FLAGS_BASE     (UAV_GROUP_CULLING_BASE + 0)
#define UAV_INDIRECT_CULLING_RESULTS_BASE    (UAV_GROUP_CULLING_BASE + 8)
#define UAV_INDIRECT_DISPATCH_MESHES_BASE    (UAV_GROUP_CULLING_BASE + 16)

#define UAV_LIGHT_GRID             (UAV_GROUP_LIGHTING_BASE + 0)
#define UAV_LIGHT_GRID_MASK        (UAV_GROUP_LIGHTING_BASE + 1)

#define UAV_SCENE_COLOR            (UAV_GROUP_SCENE_BASE + 0)
#define UAV_VBUFFER				   (UAV_GROUP_SCENE_BASE + 1)
#define UAV_INDIRECT_VISIBLE_BUFFER   (UAV_GROUP_SCENE_BASE + 3)

#define UAV_POST_TEMP0             (UAV_GROUP_POST_BASE + 0)
#define UAV_POST_TEMP1             (UAV_GROUP_POST_BASE + 1)

#endif // __BINDLESS_INDICES__